### ISSUE TITLE
DALL-E 3 Edit Support

### ISSUE THREAD

**Issue by zquestz** [pvskp/gimp-dall-e#2]
Is there any reason only DALL-E 2 is supported for editing?

The difference in quality is very noticeable when creating with DALL-E 3 then editing with DALL-E 2. =\

**Comment by pvskp** [comment]
Hi! Thanks for using the gimp-dall-e plugin. 

Unfortunally, this is a OpenAI limitation, which only provide edit capabilities to DALL-E 2 (https://platform.openai.com/docs/guides/images/edits-dall-e-2-only). 

I hope they change this in the future, but for now it will not be possible :(
